server:
  port: 8888

spring:
  application:
    name: config-server

  security:
    user:
      name: config
      password: config

  cloud:
    config:
      server:
        native:
          # Ищем и в корне, и в папке конкретного приложения.
          # Это важно, потому что файлы лежат так:
          # /config-repo/user-service/application.yml
          # /config-repo/api-gateway/application.yml
          #
          # {application} подставляется именем клиента:
          # user-service, api-gateway, notification-service.
          search-locations: file:///config-repo,file:///config-repo/{application}
  profiles:
    active: native

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.config: INFO